---
# Installs OpenVPN

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Add epel repository
  yum:
    name: epel-release
    state: present

- name: Install OpenVPN 
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - openvpn
    - unzip
    - curl
    - net-tools

- name: Cred exists
  stat:
    path: /etc/openvpn/openvpn.zip
  register: openvpen_reg

- name: Download OpenVPN PIA configurations
  get_url:
    url: https://www.privateinternetaccess.com/openvpn/openvpn.zip
    dest: /etc/openvpn
  when: openvpen_reg.stat.exists == False

- name: Extract the ZIP file
  unarchive:
    src: /etc/openvpn/openvpn.zip
    dest: /etc/openvpn
    remote_src: yes

- name: Cred exists
  stat:
    path: /etc/openvpn/cred.conf
  register: openvpen_cred_reg

- name: Copy plex repo file
  copy:
    src: files/cred.conf
    dest: /etc/openvpn/cred.conf
    owner: root
    group: root
    mode: 0400
  when: openvpen_cred_reg.stat.exists == False

- name: Create server.conf symlink
  file:
    follow: yes
    force: no
    state: link
    src: "/etc/openvpn/{{ exit_node }}"
    dest: /etc/openvpn/server.conf

- name: Setup auth user pass to point to cred.conf
  replace:
    path: "/etc/openvpn/{{ exit_node }}"
    regexp: 'auth-user-pass'
    replace: 'auth-user-pass cred.conf'

- name: Set name server 209.222.18.222
  lineinfile:
    dest: /etc/resolv.conf
    regexp: "^nameserver 209[.]222[.]18[.]222"
    line: "nameserver 209.222.18.222"
    state: present

- name: Set name server 209.222.18.218
  lineinfile:
    dest: /etc/resolv.conf
    regexp: "^nameserver 209[.]222[.]18[.]218"
    line: "nameserver 209.222.18.218"
    state: present

- name: Copy NetworkManager conf
  copy:
    src: files/NetworkManager.conf
    dest: /etc/NetworkManager/NetworkManager.conf

- name: Restart Network Manager to read new config file.
  systemd:    
    name: NetworkManager.service
    state: restarted

# - name: Reset SELinux security context labels
#   shell: restorecon -Rv /etc/openvpn

- name: Enable Openvpn service and start it
  systemd:
    enabled: yes
    name: openvpn@server.service
    state: started

- name: Copy killswitch over to remote
  template:
    src: templates/killswitch.sh
    dest: "/root/killswitch.sh"
    mode: 0744  
    owner: root
    group: root

- name: Setup cron entry for kill switch
  cron:
    job: "/root/killswitch.sh"
    day: "*"
    hour: "*"
    minute: "*"
    month: "*"
    weekday: "*"
    state: present

# curl ipecho.net/plain ; echo