
- name: Stat sonarr exists.
  stat:
    path: "{{ sonarr.install_dir }}"
  register: sonarr_reg

- name: Install Sonarr
  block:
  - name: Add RPM key
    rpm_key:
      state: present
      key: "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"

  - name: Add Sonarr repository
    yum_repository:
      name: sonarr
      description: Sonarr repo
      baseurl: http://download.mono-project.com/repo/centos/

  - name: Install Sonarr packages
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - wget 
      - mediainfo 
      - libzen 
      - libmediainfo 
      - curl 
      - gettext 
      - mono-core 
      - mono-devel 
      - sqlite.x86_64
      - git 
      - par2cmdline 
      - p7zip 
      - unar 
      - unzip 
      - tar 
      - gcc 
      - python-feedparser 
      - python-configobj 
      - python-cheetah 
      - python-dbus 
      - python-devel 
      - libxslt-devel

  - name: Add sonarr group
    group:
      name: sonarr
      state: present

  - name: Add sonarr user
    user:
      name: "{{ sonarr.user }}"
      groups: "{{ sonarr.group }},{{ media_group }}"
      shell: /sbin/nologin
      append: yes
      comment: "sonarr nologin User"
      state: present

  - name: Create Sonarr directories
    file:  
      path: "{{ sonarr.install_dir }}/bin"
      state: directory

  - name: Unarchive sonarr
    unarchive:
      src: "http://update.sonarr.tv/v2/master/mono/NzbDrone.master.tar.gz"
      remote_src: yes
      dest: /opt

  - name: Move files into proper place
    shell: "mv /opt/NzbDrone/* {{ sonarr.install_dir }}/bin"

  - name: Set directory permissions to sonarr user sonarr group
    file:
      path: "{{ sonarr.install_dir }}"
      owner: sonarr
      group: sonarr
      recurse: yes

  - name: Remove NzbDrone directory
    file:
      path: /opt/NzbDrone
      state: absent

  - name: Copy systemd sonarr service file
    template:
      src: templates/systemd-sonarr
      dest: "/etc/systemd/system/{{ sonarr.service_name }}"
      mode: 0644    

  - name: Enable sonarr service and start it
    systemd:
      daemon_reload: yes
      enabled: yes
      name: "{{ sonarr.service_name }}"
      state: started
      
  when: sonarr_reg.stat.exists == False

- name: Open firewalld ports service
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - "{{ sonarr.ports }}"