---
# Installs the plex media server.

- name: Stat plexmedia exists.
  stat:
    path: "{{ plex.install_dir }}"
  register: plex_reg

- name: Download and instlal plex media server.
  block:
  - name: Copy plex repo file
    copy:
      src: files/plex.repo
      dest: /etc/yum.repos.d/plex.repo

  - name: Install Plex Media server package
    yum:
      name: plexmediaserver
      state: present

  - name: Adding media group to plex
    user:
      name: "{{ plex.user }}"
      groups: "{{ media_group }}"
      append: yes

  - name: Set directory permissions to plex user plex group
    file:
      path: "{{ plex.install_dir }}"
      owner: "{{ plex.user }}"
      group: "{{ plex.group }}"
      recurse: yes

  - name: Enable Plex Media server.
    systemd:    
      enabled: yes
      name: "{{ plex.service_name }}"
      state: started      

  when: plex_reg.stat.exists == False

- name: Copy plex firewalld port configuration
  copy:
    src: files/plexmediaserver.xml
    dest: /etc/firewalld/services/plexmediaserver.xml

- name: Enabled firewalld plexmedia port mappings
  shell: firewall-cmd --add-service=plexmediaserver --permanent

- name: Reload Firewalld
  shell: firewall-cmd --reload
