---
# Installs nzbget 
# Default username: nzbget 
# Default Password: tegbzn6789

- name: Stat nzbget exists.
  stat:
    path: "{{ nzbget.install_dir }}/nzbget"
  register: nzbget_reg

- name: Install NZBGet
  block:
  - name: Download NZBget
    get_url:
      url: https://github.com/nzbget/nzbget/releases/download/v20.0/nzbget-20.0-bin-linux.run
      dest: /home
      mode: 0755  

  - name: Run the instlaler
    shell: "/home/nzbget-20.0-bin-linux.run --destdir {{ nzbget.install_dir }}"

  - name: Add nzbget group
    group:
      name: "{{ nzbget.group }}"
      state: present

  - name: Add nzbget user
    user:
      name: "{{ nzbget.user }}"
      groups: "{{ nzbget.group }},{{ media_group }}"
      shell: /sbin/nologin
      append: yes
      comment: "nzbget nologin User"
      state: present

  - name: Set directory permissions to nzbget user nzbget group
    file:
      path: "{{ nzbget.install_dir }}"
      owner: "{{ nzbget.user }}"
      group: "{{ nzbget.group }}"
      recurse: yes

  - name: Copy nzbget service file
    template:
      src: templates/systemd-nzbget
      dest: "/etc/systemd/system/{{ nzbget.service_name }}"
      mode: 0644

  - name: Enable nzbget service and start it
    systemd:
      daemon_reload: yes
      enabled: yes
      name: "{{ nzbget.service_name }}"
      state: started

  when: nzbget_reg.stat.exists == False

- name: Open firewalld ports nzbget service
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - "{{ nzbget.ports }}"
