---
# Installs nzbget 
# Default username: nzbget 
# Default Password: tegbzn6789

- name: Stat nzbget exists.
  stat:
    path: "{{ nzbget_install_dir }}/nzbget"
  register: nzbget_reg

- name: Install NZBGet
  block:
  - name: Download NZBget
    get_url:
      url: https://github.com/nzbget/nzbget/releases/download/v20.0/nzbget-20.0-bin-linux.run
      dest: /home
      mode: 0755  

  - name: Run the instlaler
    shell: "/home/nzbget-20.0-bin-linux.run --destdir {{ nzbget_install_dir }}"

  # - name: Add nzbget group
  #   group:
  #     name: nzbget
  #     state: present

  # - name: Add nzbget user
  #   user:
  #     name: nzbget
  #     groups: nzbget
  #     shell: /sbin/nologin
  #     append: yes
  #     comment: "nzbget nologin User"
  #     state: present

  # - name: Set directory permissions to nzbget user nzbget group
  #   file:
  #     path: "{{ nzbget_install_dir }}"
  #     owner: nzbget
  #     group: nzbget
  #     recurse: yes

  - name: Copy nzbget service file
    template:
      src: templates/systemd-nzbget
      dest: /etc/systemd/system/nzbget.service
      mode: 0644

  - name: Enable nzbget service and start it
    systemd:
      daemon_reload: yes
      enabled: yes
      name: nzbget.service
      state: started

  when: nzbget_reg.stat.exists == False

- name: Open firewalld port 6789 for service
  firewalld:
    port: 6789/tcp
    state: enabled
    permanent: true
    immediate: true

- name: Open firewalld port 563 for service
  firewalld:
    port: 563/tcp
    state: enabled
    permanent: true
    immediate: true
