---
# Main yaml file for installing the media role

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Add epel repository
  yum:
    name: epel-release
    state: present

- name: Disable SELinux
  selinux:
    state: disabled

- name: Ensure that firewalld is running and is enabled
  systemd:
    enabled: yes
    name: firewalld.service
    state: started

- import_tasks: install-sonarr.yml
- import_tasks: install-nzbget.yml
- import_tasks: install-plexmedia.yml
- import_tasks: install-couchpotato.yml
